# embulk gem install embulk-parser-none
in:
  type: file
  path_prefix: example/example.jsonl
  parser:
    type: none
out:
  type: bigquery
  mode: replace
  auth_method: json_key
  json_keyfile: /tmp/your-project-000.json
  dataset: your_dataset_name
  table: your_table_name_%Y%m%d
  compression: GZIP
  source_format: NEWLINE_DELIMITED_JSON
  auto_create_dataset: true
  auto_create_table: true
  template_table: your_table_name
  payload_column: true
  skip_load: true # for debug
